name: Publish update

on:
  push:
    branches: ['main']
    paths:
      - 'mobile/**'
      - '!mobile/**/*.md'

concurrency:
  cancel_in_progress: true
  group: ${{ workflow.filename }}-${{ github.ref }}

jobs:
  publish_update:
    name: Publish OTA update
    type: update
    params:
      channel: preview
      platform: ios
      message: ${{ github.event.head_commit.message || 'Manual update' }}
